# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - sskaz400prep

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Install Python dependencies
      run: |
        python3 -m venv env
        .\env\Scripts\activate
        pip install -r requirements.txt

    - name: Zip the application files
      run: Compress-Archive .\* app.zip

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sskaz400prep'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_23386efe6e1141e28b553a54f02d1c27 }}
        package: '.\myapp.zip'